import { useRouter } from "next/router";
import Link from "next/link";
import Head from 'next/head';
const CoffeeStore = () => {
  const router = useRouter();
  console.table(router);
  return (
    <div>
            <Head>
        <title>Coffee Shop - {router.query.id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/beans.png" />
      </Head>
      <div>{router.query.id}</div>
      <Link href="/">
        <a>Back to home</a>
      </Link>
    </div>
  );
};

export default CoffeeStore;
